version = 1.0
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-expense-tally-app"
s3_bucket = "s3-expense-tally-app"
s3_prefix = "app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
