AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  expense-tally-read-s3-db
  SAM Template for expense-tally-read-s3-db

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  ExpenseManagerDatabase:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-expense-tally-expense-manager-database
  ReadDatabaseFileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: expense_tally.aws.lambda.read_s3_db.app.App::handleRequest
      Runtime: java11
      MemorySize: 1024 # Give more memory because need to read from database file
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket:
              Ref: ExpenseManagerDatabase  # This must be the name of an S3 bucket declared in the same template file
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix      # or "suffix"
                    Value: personal_finance.db  # The value to search for in the S3 object key names

Outputs:
  ReadDatabaseFileFunction:
    Description: "Read Database File Lambda Function ARN"
    Value: !GetAtt ReadDatabaseFileFunction.Arn
  ReadDatabaseFileFunctionIamRole:
    Description: "Implicit IAM Role created for Read Database File Lambda function"
    Value: !GetAtt ReadDatabaseFileFunctionRole.Arn
