AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for Expense Tally

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  ExpenseTallyData:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-expense-tally-data
      VersioningConfiguration:
        Status: Enabled
  ReadDatabaseFileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: expense_tally.aws.em_change_processor.app.App::handleRequest
      Runtime: java11
      MemorySize: 512 # Give more memory because need to read from database file
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          expense_manager_db_host_url: expense-tally.cluster-cknvvjlyuzwc.us-east-1.rds.amazonaws.com
          expense_manager_db_username: admin
          expense_manager_db_password: password
          expense_manager_db_name: expense_tally
      Events:
        UpdateDatabaseObject:
          Type: S3
          Properties:
            Bucket:
              Ref: ExpenseTallyData  # This must be the name of an S3 bucket declared in the same template file
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix      # or 'suffix'
                    Value: .db  # The key to search for in the S3 object key names
  ReadCsvFileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: expense_tally.aws.csv_reader.app.App::handleRequest
      Runtime: java11
      MemorySize: 384 # Give more memory because need to read from database file
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          expense_manager_db_host_url: expense-tally.cluster-cknvvjlyuzwc.us-east-1.rds.amazonaws.com
          expense_manager_db_username: admin
          expense_manager_db_password: password
          expense_manager_db_name: expense_tally
      Events:
        UpdateCsvObject:
          Type: S3
          Properties:
            Bucket:
              Ref: ExpenseTallyData  # This must be the name of an S3 bucket declared in the same template file
            Events: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix      # or 'prefix'
                    Value: .csv  # The key to search for in the S3 object key names

Outputs:
  ReadDatabaseFileFunction:
    Description: 'Read Database File Lambda Function ARN'
    Value: !GetAtt ReadDatabaseFileFunction.Arn
  ReadDatabaseFileFunctionIamRole:
    Description: 'Implicit IAM Role created for Read Database File Lambda function'
    Value: !GetAtt ReadDatabaseFileFunctionRole.Arn
  ReadCsvFileFunction:
    Description: 'Read CSV File Lambda Function ARN'
    Value: !GetAtt ReadCsvFileFunction.Arn
  ReadCsvFileFunctionIamRole:
    Description: 'Implicit IAM Role created for Read CSV File Lambda function'
    Value: !GetAtt ReadCsvFileFunctionRole.Arn
